version: '3.8'

services:
  db:
    image: postgres:15
    container_name: my_postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - test_network
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: my_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - test_network

volumes:
  postgres_data:

networks:
  test_network: